name: StudioViews
favicon: null
layout_spectrum: 0.7033720929175615
typography_spectrum: 0.9164112433791161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.833121795207262
  lightness: 0.3087901303078979
  saturation: 0.4759147719014436
  rhythmicContrast: 0.6768433356191963
purpose: []
